ZHSQ_URL: http://api.isccmp.isc.glb.cmos:50002/isccmp/index.html#/login
userAcct: CS000400399
userPwd: 1qaz!QAZ
smsCode: 123456

log:
  file_name: test.log
  backup: 5
  console_level: WARNING
  file_level: DEBUG
  pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
ip: 127.0.0.1
port: 8080
